# specify the version of docker-compose
version: "3.8"

# define the services/containers to be run
services:
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  api: 
    build: ./backend
    ports: 
      - 4000:4000
    env_file:
      - ./backend/.env
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

